apiVersion: v1
kind: Namespace
metadata:
  name: fraud-detection
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fraud-detection
  namespace: fraud-detection
  labels:
    app: fraud-detection
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fraud-detection
  template:
    metadata:
      labels:
        app: fraud-detection
    spec:
      containers:
      - name: fraud-detection
        image: registry.digitalocean.com/grifflesctf2025/fraud-detection:latest
        ports:
        - containerPort: 8000
        resources:
          limits:
            cpu: "0.5"
            memory: "256Mi"
          requests:
            cpu: "0.2"
            memory: "128Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
  namespace: fraud-detection
spec:
  selector:
    app: fraud-detection
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP